apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: sogwujiakwu/solar-system:13-af20a972c59574738531455d058fded7cff7211d
        name: solar-system
        ports: 
        - containerPort: 80
