apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: sogwujiakwu/solar-system:14-46b0262e3d7ab534396971b25c527f7e435846bc
        name: solar-system
        ports: 
        - containerPort: 80
